language: cpp

os:
  - linux
  - osx

dist: xenial
osx_image: xcode10.1

compiler:
  - gcc
  - clang

matrix:
  exclude:
  - compiler: gcc
    os: osx

env: BOOSTNAME=boost_1_70_0

install:
  - wget https://dl.bintray.com/boostorg/release/1.70.0/source/${BOOSTNAME}.zip
  - unzip -q ${BOOSTNAME}.zip
  - cd ${BOOSTNAME}
  - sudo ./bootstrap.sh
  - sudo ./b2 install -j 2 -d0 --with-math
  - cd ..

script:
  - make -j
  - make test
